spring.application.name=getcard

# Configura��o do banco de dados MySQL
spring.datasource.url=jdbc:postgresql://dpg-cil7camidees73f4e0m0-a.oregon-postgres.render.com:5432/getcarddb
spring.datasource.username=getcarddb_user
spring.datasource.password=SU6sZBqoCCHjsVciEe4nixErFi1x
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.jdbc.time_zone=America/Sao_Paulo

google.service.account.key.path=src/main/resources/credenciais.json
google.drive.folder-id=1Gypp9zae4xDzYKIP3gBV5V1wu7Wu5lmf


# Permitir acesso sem autentica��o
spring.security.user.name=admin
spring.security.user.password=admin


